# Generated by Django 4.1.7 on 2023-03-05 17:27

from django.db import migrations
import home_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', home_page.models.CustomUserManager()),
            ],
        ),
    ]
